version: '3.8'

services:
  # 1. BAZA PODATAKA
  db:
    image: postgres:alpine
    container_name: commanders_defense_db
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=CDDatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # 2. PGADMIN - Pregled baze
  pgadmin:
    image: dpage/pgadmin4
    container_name: commanders_defense_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS:-admin}
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data: